### ISSUE TITLE
Memory free issue in Nativelibraries

### ISSUE THREAD

**Issue by karthikeyan1241997** [libimobiledevice-win32/imobiledevice-net#57]
I am using imobiledevice-net in VS2017.whenever I tried to call some native library's free function such as np_client_free(), it throws an exception saying that System.AccessViolationException

I m providing some debug info below..

```
Releasing NotificationProxyClientHandle 2470434744832 using iMobileDevice.LibiMobileDevice. This object was created at    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at iMobileDevice.NotificationProxy.NotificationProxyClientHandle..ctor()
   at iMobileDevice.NotificationProxy.NotificationProxyNativeMethods.np_client_new(iDeviceHandle device, LockdownServiceDescriptorHandle service, NotificationProxyClientHandle& client)
   at iMobileDevice.NotificationProxy.NotificationProxyApi.np_client_new(iDeviceHandle device, LockdownServiceDescriptorHandle service, NotificationProxyClientHandle& client)
   .
   .
   .

Exception thrown: 'System.AccessViolationException' in iMobileDevice-net.dll
An unhandled exception of type 'System.AccessViolationException' occurred in iMobileDevice-net.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

**Comment by qmfrederik** [comment]
All the handles implement  `IDisposable` and have a `.Dispose()` method,  which will call the relevant `free` function on your behalf.

This means you don't need to manually free the handles yourself. Doing so would result in a double-free and the exception you are seeing.

**Comment by qmfrederik** [comment]
@karthikeyan1241997 I believe I've answered your question, feel free to reopen if not.
